### PR TITLE
Make recipe `noarch`

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by MCRE-BE** [comment]
closed #55 in favor of this one.
Thanks @dhirschfeld

**Comment by fkiraly** [comment]
THANKS!

I was already considering to set my computer on fire and see if that sacrifice pleases the `conda` gods, but I suppose this is much better.

Given the time you've invested and the fact that you're clearly more experienced with `conda` than I, might I add the two of you as maintainers of this feedstock?

**Comment by MCRE-BE** [comment]
> Given the time you've invested and the fact that you're clearly more experienced with `conda` than I, might I add the two of you as maintainers of this feedstock?

I have absolutly no experience with conda 😅 Just power of deduction and a cool boss that allows me to do what I want 🫣

**Comment by fkiraly** [comment]
> I have absolutly no experience with conda 😅 Just power of deduction and a cool boss that allows me to do what I want

Sounds good enough? Most of what I do on conda is also power of deduction plus trial and error...

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
