### PR TITLE
[FIX] Test noarch everywhere

### PR DESCRIPTION
**Pull request by MCRE-BE**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MCRE-BE** [comment]
image

😭 😭

**Comment by MCRE-BE** [comment]
@conda-forge-admin, please rerender

**Comment by MCRE-BE** [comment]
hhmmmm the rerender puts Numpy to 1.26
but all the sub-packages have disappeared. Strange ?

**Comment by dhirschfeld** [comment]
> hhmmmm the rerender puts Numpy to 1.26

I'm not sure what you mean by this?

**Comment by dhirschfeld** [comment]
> but all the sub-packages have disappeared. Strange ?

Also, not sure what you're meaning? If you mean that all the CI configuration for arch-specific packages has been deleted, then that's as expected - a `noarch` package gets built on `linux-64` and because it's `noarch` it can be installed on any platform.

**Comment by dhirschfeld** [comment]
I have a slightly more correct version over in #56 - it gets rid of other extraneous config that only serves to confuse the situation.

Since I'm not a maintainer here, it was easier to just put in a new PR.

**Pull request closed without merging**
