### PR TITLE
MNT: noarch recipe

### PR DESCRIPTION
**Pull request by fkiraly**
Turns the recipe into `noarch`, as @dhirschfeld suggested here: https://github.com/sktime/skbase/issues/330#issuecomment-2118676169

### CODE REVIEW

**Comment by fkiraly** [comment]
Well, what's this all about now...
FYI @MCRE-BE, @yarnabrina

**Comment by MCRE-BE** [comment]
> Well, what's this all about now...
> 
> FYI @MCRE-BE, @yarnabrina

The joy of IT 😂

**Comment by MCRE-BE** [comment]
Outside of the obvious bad taste joke : 

- Only OSX_arm64 builds have failed
- All show the error message ` Bad CPU type in executable`

So likely, the changes you made broke a dependency that is needed to work on Appe Silicone processors. No idea how that work's, that's above my skill level.

**Comment by fkiraly** [comment]
Hm, I now copied a block from `sktime` that seems related:

```
    build:
      #FIXME: Extras environment not resolvable on aarch. Needs someone with
      #arm machine to tests.
      skip: true  # [aarch64]
      noarch: python
```

I really feel like a mad alchemist here, throwing stuff into the cauldron and cackling while it changes colour. I have no idea whether it will heal me or kill me.

**Comment by dhirschfeld** [comment]
You need to rerender the recipe after adding `noarch` you'll also need to remove the selectors and hence the build scripts (the build command should be inline in the recipe)

**Comment by fkiraly** [comment]
Thanks for the advice, @dhirschfeld.

Ok, point taken abour rerendering.

I do not get what this means, can you please explain?
>  you'll also need to remove the selectors and hence the build scripts (the build command should be inline in the recipe)

**Comment by MCRE-BE** [comment]
Stupid question but I'm drawing inspiration from [geopandas](https://github.com/conda-forge/geopandas-feedstock/blob/main/recipe/meta.yaml) that seems to have the same set-up as this repo. It seems very complex though when comparing to other big repo's (xgboost, numpy, ...)

Shouldn't we change this to
https://github.com/conda-forge/skbase-suite-feedstock/blob/16d2ddf3bc313bfa93db44c828c4001335f9f74f/recipe/meta.yaml#L12-L15

```yaml
build:
  noarch: python
  number: 0
  skip: true  # [(py==37 and aarch64)]
  skip: true  # [py<37 or py>312]
```

and you might also need a build command here.
https://github.com/conda-forge/skbase-suite-feedstock/blob/16d2ddf3bc313bfa93db44c828c4001335f9f74f/recipe/meta.yaml#L26C1-L35C29

**Comment by fkiraly** [comment]
hmm, let's try that. You can also make PR with good guesses and we see what happens.

**Comment by fkiraly** [comment]
ok...

now it does not fail on 3.12, but on aarm64 (which was skipped previously)

**Comment by fkiraly** [comment]
still does not work...

**Comment by dhirschfeld** [comment]
Just a friendly reminder that ***none of your changes will have any effect until you rerender the recipe.***

**Comment by fkiraly** [comment]
> Just a friendly reminder that _**none of your changes will have any effect until you rerender the recipe.**_

What does that concretely mean, I am not familiar with the `conda` lingo. Is it merging and then asking the bot to "rerender"?

**Comment by fkiraly** [comment]
continuing here: https://github.com/conda-forge/skbase-suite-feedstock/pull/54

**Comment by dhirschfeld** [comment]
> What does that concretely mean, I am not familiar with the `conda` lingo. Is it merging and then asking the bot to "rerender"?

Yes, you just add a comment in a PR with the words:
```
@conda-forge-admin, please rerender
```

And the bot will come along and add a commit to the PR with the re-rendered recipe.

**Comment by fkiraly** [comment]
oh, no need to merge and rerender from issue, I see.

**Pull request merged**
